
services:
  wireguard-port-forward:
    image: holmanw/wireguard-port-forward:latest
    container_name: wireguard-port-forward
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=1a
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.14.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
      - PORTS=80/tcp,443/tcp
    volumes:
      - ./config:/config
      # - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp #wg port
      # - 34202:34202/tcp  #port forwarding port
      # - 34202:34202/udp  #port forwarding port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped